FactoryGirl.define do
  factory :local_survey do
    jb_region "MyString"
    national_jb "MyString"
    local_jb "MyString"
    nun_local_events 1
    num_related 1
    age_group 1
    num_jbers 1
    gender_ratio "MyString"
    represented false
    good_relationship false
    awareness_of_meetings false
    num_local_attenders 1
    num_regional_attenders 1
    num_international_attenders 1
    participates false
    knowGoals false
    GQ1 false
    GQ2 false
    GQ3 false
    GQ4 false
    GQ5 false
    GQ6 false
    GQ7 false
    GQ8 false
    GQ9 false
    G2Q1 false
    G2Q2 false
    G2Q3 false
    G2Q4 false
    G2Q5 false
    G2Q6 false
    G3Q1 false
    G3Q2 false
    G3Q3 false
    G3Q4 false
    G3Q5 false
    G4Q1 false
    G4Q2 false
    G4Q3 false
    G4Q4 false
    G4Q5 "MyString"
    G4Q6 "MyString"
  end
end
