default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: mixed_nuts_development

test:
  <<: *default
  database: mixed_nuts_test

production:
  <<: *default
  database: mixed_nuts
